---
  version: "3"
  services:
    nginx:
      image: docker.io/library/nginx:mainline
      container_name: nginx
      volumes:
        - /opt/nginx/nginx.conf:/etc/nginx/nginx.conf
        - /opt/nginx/server.crt:/etc/nginx/server.crt
        - /opt/nginx/server.key:/etc/nginx/server.key
      ports:
        - 80:80
        - 443:443
      restart: unless-stopped
    jenkins:
      image: docker.io/jenkins/jenkins:centos
      container_name: jenkins
      volumes:
        - /opt/jenkins:/var/jenkins_home
      expose:
        - 8080
      poerts:
        - 50000:50000
      restart: unless-stopped
